### PR TITLE
Implement base rosetta signature schemes

### LINKED ISSUE #35: Implement signature schemes as seen in rosetta-sdk-go
This will allow us to test implementations other than just Aleo.

Time estimate: 8 hours

### PR DESCRIPTION
**Pull request by jels-boolean**
Fixes #35

### CODE REVIEW

**Comment by jels-boolean** [comment]
Time taken: 9 hours

**Comment by jels-boolean** [comment]
I will create an issue to test all of these - for the sake of time tracking though I'll separate it from this PR.

**Review by mowkoshka — APPROVED** [review]
LGTM. Should we eventually make it, so each key is a separate feature? We could make it, so each different type is a feature. The `keys` feature could then contain each of those?

**Comment by jels-boolean** [comment]
@mowkoshka This was my eventual plan - I'm just putting everything under an `sdk` umbrella for now cause it makes development a bit easier, but when the codebase is more built out I'll spend some time feature gating more granularly.

**Pull request merged**
